# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  name: wso2am-api-key-manager
  labels:
    app: wso2am-api-key-manager
    tier: wso2am-api-key-manager
spec:
  type: NodePort
  ports:
    # ports that this service should serve on
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32001
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32002
    -
      name: 'thrift-key-mgt'
      port: 10397
      targetPort: 10397
      nodePort: 32003
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: wso2am-api-key-manager
    tier: wso2am-api-key-manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2am-api-key-manager
  labels:
    app: wso2am-api-key-manager
    tier: wso2am-api-key-manager
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wso2am-api-key-manager
        tier: wso2am-api-key-manager
    spec:
      containers:
      - image: us.gcr.io/steam-talent-167709/wso2am-api-key-manager-kubernetes-pattern-3:2.1.0
        name: wso2am-api-key-manager
        imagePullPolicy: Always
        env:
        -
          name: KUBERNETES_MASTER_SKIP_SSL_VERIFICATION
          value: "true"
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        -
          containerPort: 10397
          protocol: "TCP"
