apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: 10000
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/wso2user/shared-artifacts/gateway
